name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Assignment4
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Assignment4

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Bookclub.Web/package-lock.json

      - name: Install + Generate
        working-directory: Bookclub.Web
        run: |
          npm ci
          npm run generate
          cp public/staticwebapp.config.json .output/public/staticwebapp.config.json

      - name: Deploy prebuilt output
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FOREST_0B7132C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "Bookclub.Web/.output/public"
          api_location: ""
          output_location: ""
          skip_app_build: true

